# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "F:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/.Xil/Vivado-10112-LB-201704111542/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z010clg400-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/100a
    f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/ed72/hdl
    f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/7e3a/hdl
  } {
      D:/Xilinx/Vivado/2016.4/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      D:/Xilinx/Vivado/2016.4/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/100a
    f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/ed72/hdl
    f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/7e3a/hdl
  } {
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/8c13/hdl/verilog/processing_system7_v5_5_aw_atc.v
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/8c13/hdl/verilog/processing_system7_v5_5_b_atc.v
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/8c13/hdl/verilog/processing_system7_v5_5_w_atc.v
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/8c13/hdl/verilog/processing_system7_v5_5_atc.v
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/8c13/hdl/verilog/processing_system7_v5_5_trace_buffer.v
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/hdl/verilog/processing_system7_v5_5_processing_system7.v
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/synth/system_processing_system7_0_0.v
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/1923/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_v_axi4s_vid_out_0_0/synth/system_v_axi4s_vid_out_0_0.v
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_clk_wiz.v
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.v
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/ed72/hdl/axi_vdma_v6_2_rfs.v
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/3c71/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_v_vid_in_axi4s_0_0/synth/system_v_vid_in_axi4s_0_0.v
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/e147/xlconstant.v
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_xlconstant_1_0/sim/system_xlconstant_1_0.v
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/5dd2/IPSRC/cmos_decode_v1.v
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/5dd2/IPSRC/count_reset_v1.v
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/5dd2/IPSRC/OV_Sensor_ML.v
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_OV_Sensor_ML_0_2/synth/system_OV_Sensor_ML_0_2.v
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/7ee0/hdl/generic_baseblocks_v2_1_vl_rfs.v
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/7e3a/hdl/axi_infrastructure_v1_1_vl_rfs.v
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/0b6b/hdl/axi_register_slice_v2_1_vl_rfs.v
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/39ba/hdl/axi_data_fifo_v2_1_vl_rfs.v
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/896d/hdl/axi_crossbar_v2_1_vl_rfs.v
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_xbar_0/synth/system_xbar_0.v
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_xbar_1/synth/system_xbar_1.v
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/df1b/hdl/axi_protocol_converter_v2_1_vl_rfs.v
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_auto_pc_0/synth/system_auto_pc_0.v
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/8479/hdl/axi_clock_converter_v2_1_vl_rfs.v
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/a4c8/hdl/axi_dwidth_converter_v2_1_vlsyn_rfs.v
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_auto_us_0/synth/system_auto_us_0.v
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_auto_pc_1/synth/system_auto_pc_1.v
      F:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/hdl/system.v
      F:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/hdl/system_wrapper.v
    }
      rt::read_vhdl -lib lib_cdc_v1_0_2 f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/52cb/hdl/lib_cdc_v1_0_rfs.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0_10 f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/04b4/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib {
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_50M_0/synth/system_rst_processing_system7_0_50M_0.vhd
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_v_tc_0_0/synth/system_v_tc_0_0.vhd
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_util_vector_logic_0_0/synth/system_util_vector_logic_0_0.vhd
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_axi_vdma_0_1/synth/system_axi_vdma_0_1.vhd
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/d277/IPSRC/TMDSEncoder.vhd
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/d277/IPSRC/SerializerN_1.vhd
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/d277/IPSRC/DVITransmitter.vhd
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/d277/IPSRC/hdmi_tx.vhd
      f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ip/system_HDMI_FPGA_ML_0_0/synth/system_HDMI_FPGA_ML_0_0.vhd
    }
      rt::read_vhdl -lib blk_mem_gen_v8_3_5 f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/6273/hdl/blk_mem_gen_v8_3_vhsyn_rfs.vhd
      rt::read_vhdl -lib fifo_generator_v13_1_3 f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/564d/hdl/fifo_generator_v13_1_vhsyn_rfs.vhd
      rt::read_vhdl -lib axi_lite_ipif_v3_0_4 f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/0ba0/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib v_tc_v6_1_10 f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/d9f8/hdl/v_tc_v6_1_vh_rfs.vhd
      rt::read_vhdl -lib util_vector_logic_v2_0 f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/1d19/hdl/util_vector_logic.vhd
      rt::read_vhdl -lib lib_pkg_v1_0_2 f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/832a/hdl/lib_pkg_v1_0_rfs.vhd
      rt::read_vhdl -lib lib_fifo_v1_0_7 f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/5ab6/hdl/lib_fifo_v1_0_rfs.vhd
      rt::read_vhdl -lib lib_bmg_v1_0_7 f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/38e8/hdl/lib_bmg_v1_0_rfs.vhd
      rt::read_vhdl -lib lib_srl_fifo_v1_0_2 f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/6039/hdl/lib_srl_fifo_v1_0_rfs.vhd
      rt::read_vhdl -lib axi_datamover_v5_1_13 f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/bf41/hdl/axi_datamover_v5_1_vh_rfs.vhd
      rt::read_vhdl -lib axi_vdma_v6_2_10 f:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/Miz_sys.srcs/sources_1/bd/system/ipshared/ed72/hdl/axi_vdma_v6_2_rfs.vhd
      rt::read_vhdl -lib xpm D:/Xilinx/Vivado/2016.4/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top system_wrapper
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "F:/miz701N/7010/s3/S03_CH07_AXI_VDMA_OV5640/Miz_sys/.Xil/Vivado-10112-LB-201704111542/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
